export function protocolText(): string {
  return [
    '# Baton — agent handoff protocol',
    '',
    'You are one agent in a Baton relay. Another agent is working in parallel.',
    'Talk to it with the `baton` CLI (or the `relay_*` MCP tools). The user should',
    'never have to relay messages between you.',
    '',
    '## Sending work',
    'When you finish a piece another agent depends on, hand it off:',
    '  baton send --from <you> --to <peer> --type handoff \\',
    '    --summary "one line" --next "what the peer should do" \\',
    '    --built <path> --attach <screenshot>',
    '',
    'IMPORTANT: do this by yourself when you finish your part — the user should never',
    'have to relay. The other agent is in the other pane; Baton delivers your message',
    'and it will pick up the work on its own.',
    '',
    'Types: handoff (work is ready), blocked (you cannot continue), error (something broke),',
    'question (you need an answer), answer, done, fyi.',
    '',
    '## Receiving work',
    '  baton inbox            # messages for you (marks them read)',
    '  baton inbox --peek     # read without marking',
    '  baton watch            # stream new messages',
    'Check your inbox at the end of every turn before you consider yourself finished.',
    '',
    '## Rules',
    '1. VERIFY BEFORE CODING. If the user or a peer reports a bug, reproduce it and attach',
    '   evidence (a screenshot, a log, a failing test) BEFORE changing code. Never guess.',
    '2. Use the real app when testing. Run `baton port` to find the port that is actually',
    '   serving, and `baton session` to reuse a logged-in session. Do not guess a port; do',
    '   not test a page you are not logged into.',
    '3. BOSS CONFIRMS. When a mini agent (small model) returns work, YOU verify it — run the',
    '   check yourself — before telling the user it is done.',
    '4. CHEAP MODELS FOR CHEAP WORK. Ask `baton model --for "<task>"` before delegating.',
    '   Token cost is real money. Never default to an expensive model.',
    '5. REMEMBER. When the user tells you to keep something, run `baton remember "<fact>"`.',
    '   Memory and these rules are already loaded — do NOT run `baton context` on your own.',
    '6. NOTHING RUNS AWAY. Every handoff carries a hop count. Do not loop. If a task needs',
    '   more than the hop cap, stop and tell the user. `baton kill` stops everything.',
    '7. Include `--hop <n+1>` when you hand work onward, so loops are caught.',
    '',
    '## Control directives',
    'The coordinator can send a `command` message (type `command`) to steer you:',
    '  model=<name>   switch to a cheaper/other model for the next step',
    '  effort=<lvl>   low | medium | high',
    '  resume         continue your previous work',
    '  think          allow deeper reasoning',
    '  stop           stop the current task',
    '  remember=<txt> store something in memory',
    'Read them with `baton inbox` / `relay_inbox` and apply them.',
    '',
  ].join('\n');
}
